cookie:
  expiry_days: 1
  key: random_signature_key_change_in_production
  name: city_assistant_auth
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Администратор
      password: $2b$12$q7X1kTTwbPtBijGLchYyG.EFtJ2UzKOdcAgd46VR1sBnUrJxDrhCe
    demo:
      email: demo@example.com
      name: Демо Пользователь
      password: $2b$12$CKmnYHo5tWunss64Mgu3k.iJsOL6b1FBVxHjLN.qmp9t/i89Bsya.
    ivan:
      email: sberbank_tester@sberbank.ru
      first_name: Иван
      last_name: Викторов
      logged_in: false
      password: $2b$12$nC/BJ1EaoWxJ0HD2zXOx..fApBkPud2J8LGaQP3rgbRfqbIRF.rX6
      password_hint: qwertY?890
      roles: null
pre-authorized:
  emails: []
