[project]
name = "langgraph-app"
version = "0.1.0"
description = "LangGraph Server - основной API с графами агента"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "chromadb>=1.3.5",
    "gigachat>=0.1.43",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "langchain>=1.1.0",
    "langchain-chroma>=1.0.0",
    "langchain-classic>=1.0.0",
    "langchain-community>=0.4.1",
    "langchain-gigachat>=0.3.13a1",
    "langgraph>=1.0.4",
    "langgraph-checkpoint-sqlite>=3.0.0",
    "langgraph-sdk>=0.2.10",
    "langsmith>=0.4.49",
    "numpy>=2.3.5",
    "openrouteservice>=2.3.3",
    "pendulum>=3.1.0",
    "polyline>=2.0.4",
    "pydantic<=2.11.10",
    "pymorphy2>=0.9.1",
    "pymorphy2-dicts-ru>=2.4.417127.4579844",
    "python-dotenv>=1.2.1",
    "rank-bm25>=0.2.2",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "structlog>=25.5.0",
    "ymaps>=1.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/langgraph_app"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""
